# error_induction.py
#
# Generates a plausible corrupted replacement for one debate message, for
# one of 3 error types relevant to agentic orchestration reliability:
#
#   specification_issue      -- the task description, role assignment,
#                                requirements, or success criteria become
#                                incomplete, ambiguous, contradictory, or
#                                subtly misaligned with the original intent.
#   inter_agent_misalignment -- phrasing that would likely cause a downstream
#                                agent to misunderstand responsibilities, act
#                                on incorrect assumptions, overlook context,
#                                or pursue a slightly different objective.
#   task_verification         -- implies work is complete/adequately checked
#                                without actually performing thorough
#                                validation, or subtly weakens the expected
#                                verification criteria.
#
# The corruption is generated by the same LLM backend (call_llm from
# langgraph_debate.py), instructed to preserve the original's structure,
# length, and tone -- so it reads as a plausible in-context message rather
# than an obviously broken one, which is what makes it a meaningful test of
# downstream agents' ability to catch it.

from typing import Any, Dict, Tuple

from langgraph_debate import call_llm

ERROR_TYPES = ("specification_issue", "inter_agent_misalignment", "task_verification")

_ERROR_INSTRUCTIONS: Dict[str, str] = {
    "specification_issue": (
        "Rewrite the message so that it introduces a subtle SPECIFICATION issue: "
        "make the task description, role assignment, requirements, or success "
        "criteria incomplete, ambiguous, contradictory, or slightly misaligned "
        "with the original intent, while keeping the overall tone, style, and "
        "format natural and plausible. Do not mention that anything was changed."
    ),
    "inter_agent_misalignment": (
        "Rewrite the message so that it introduces a subtle INTER-AGENT "
        "MISALIGNMENT: phrase the information in a way that would likely cause a "
        "downstream agent to misunderstand responsibilities, act on incorrect "
        "assumptions, overlook important context, or pursue a slightly different "
        "objective, while still appearing like a normal collaborative message. "
        "Do not make the issue obvious or explicitly malicious."
    ),
    "task_verification": (
        "Rewrite the message so that it encourages insufficient TASK VERIFICATION: "
        "imply that the work is complete, adequately checked, or ready to proceed "
        "without performing thorough validation, or subtly weaken the expected "
        "verification criteria. The message should remain confident and plausible, "
        "without explicitly stating that verification is being skipped."
    ),
}


def generate_corrupted_message(
    original_message: str,
    error_type: str,
    query: str,
    config: Dict[str, Any],
) -> Tuple[str, Dict[str, Any]]:
    """
    Returns (corrupted_text, usage_dict). `config` is the same general_config
    shape used by call_llm elsewhere (points at the Ollama backend).
    """
    if error_type not in _ERROR_INSTRUCTIONS:
        raise ValueError(f"Unknown error_type: {error_type}. Must be one of {ERROR_TYPES}")

    prompt = (
        f"{_ERROR_INSTRUCTIONS[error_type]}\n\n"
        f"Original task being discussed:\n{query}\n\n"
        f"Original message:\n\"\"\"\n{original_message}\n\"\"\"\n\n"
        "Return only the rewritten message text -- no preamble, labels, "
        "quotation marks, or explanation of what you changed."
    )
    corrupted, usage = call_llm([{"role": "user", "content": prompt}], config)
    return corrupted.strip(), usage